In [ ]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.
import numpy as np
import pandas as pd

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [ ]:
my_array = np.zeros(10, dtype=int)
my_array[4] = 1



[0 0 0 0 1 0 0 0 0 0]


### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [24]:
# solution
matrix = np.arange(16).reshape(4, 4)

### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [ ]:
# solution
# addition: arr1 + arr2

# subtraction: arr1 - arr2 

# division: arr1 / arr2

# multiplication: arr1 * arr2

arr1 = np.array([[41, 30, 10], [6, 35, 23], [23, 9, 10]])

arr2 = np.array([[4, 29, 2], [5, 13, 3], [24, 16, 7]])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [ ]:
# solution
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr[2:7]

array([[25, 30, 60]])

### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [22]:
# solution

# NB: round the mean to two decimal places
arr = np.array([[15, 18, 20], 
                [15, 30, 8], 
                [25, 30, 60]])

mean_value = np.mean(arr)
sum_value = np.sum(arr)
max_value = np.max(arr)

# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [ ]:
# solution
aa = pd.Series(data = [10, 20, 30, 40, 50], index=["a", "b", "c", "d", "e"])

### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [ ]:
# solution
df = pd.read_csv('./data/data.csv')


FileNotFoundError: [Errno 2] No such file or directory: 'data/data. csv'

### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [20]:

first_three_rows = df.head(3)

### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [27]:
# solution
df['Tax'] = df['Salary'] * 0.10


#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [ ]:
# solution
filtered_df = df[df['Age'] > 36]

# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [30]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()


Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [28]:
# solution
total_sales_per_region = sales_data.groupby("Region")["Sales"].sum()

mean_sales_per_region = sales_data.groupby("Region")["Sales"].mean()


NameError: name 'sales_data' is not defined

### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [ ]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2), orders.head(2))

CustomerID CustomerName
0           1        Alice
1           2          Bob

OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400

In [ ]:
# solution
df = pd.merge(customers, orders, on="CustomerID", how="left")


### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [ ]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(2), departments.head(2))

EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2

DeptID DeptName
0       1       HR
1       2  Finance

In [ ]:
# solution
merged_data = pd.merge(employees, departments, on="DeptID", how="left")

### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [ ]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

In [31]:
# solution
pivot_table = sales_pivot_data.pivot_table(values="Sales", index="Region", columns="Product", aggfunc="sum", fill_value=0)

NameError: name 'sales_pivot_data' is not defined